<?php
/*
the user shouldn't write directly into the code!
*/

// set up up to three users (user1, user2, user3) with (password1, password2, password3)
$user1="max";
$password1="mustermann";

$a=10; //how many visitors until highlight

$save=true; //if reset/initialization is saved or not (true=saved; false=not saved)

/*************************************************
IMPORTANT!!! change the $save value to true after initialization!!!

(risk of hacking)
*************************************************/

?>